### ISSUE TITLE
Compatibility between 2.0 and master

### ISSUE THREAD

**Issue by goetas** [Masterminds/html5-php#101]
Should we create some compatibility wrapper to have an easy upgrade from 2.x to 3.0? It looks that almost everybody is still using the 2.x version

**Comment by technosophos** [comment]
How hard do you think that would be?

**Comment by stof** [comment]
this issue should be closed, as the master branch is now 2.x again.

And the 2.x branch should be deleted.

**Comment by goetas** [comment]
Right
