### ISSUE TITLE
HTML5 Tools + Drupal 7 + HTML5 PHP breaks </address> tag

### ISSUE THREAD

**Issue by sylus** [Masterminds/html5-php#109]
It seems when using HTML5 Tools + HTML5 PHP for Drupal 7 that address tags are broken.

We originally added the HTML5 PHP library to fix issues with video tags which worked. Except now it has been proven when saving a piece of content with the opening + closing address tags that the closing tags get removed on node render. CKEditor source view shows the close address tag as still present. On node view and inspect page source the closing address tag is removed.

Was wondering if had any ideas about this? ^_^

**Comment by mattfarina** [comment]
@sylus Can you point me to the code using `Masterminds\HTML5` that's causing this problem? Is it in a module?

If you look in `Drupal\Component\Utility\Html` you'll see it uses `\DOMDocument` instead of the html5 parser here. For example, [see the load function](https://github.com/drupal/drupal/blob/8.1.0/core/lib/Drupal/Component/Utility/Html.php#L252).

I'm curious where this is happening.

**Comment by sylus** [comment]
Hey thanks for the response.

We are using a patch to get html5_tools to work with html5-php from this issue:

http://drupal.org/node/2415305
https://www.drupal.org/files/issues/replace_core_text-2415305-7.patch

When looking at the markup for the body field in devel I see the following:

```sh
value (String, 40 characters ) <address>Testing address tag</address>
...
safe_value (String, 39 characters ) <address>Testing address tag

So it is the safe value which I believe gets called by the following:

```sh
function html5_tools_filter_info() {
...
  $filters['filter_html5corrector'] = array(
    'title' =>  t('Correct faulty and chopped off HTML5'),
    'process callback' => '_html5_tools_filter_htmlcorrector',
    'weight' => 10,
  );
...
}
```

```sh
/**
 * Implements callback_filter_process().
 *
 * Scans the input and makes sure that HTML tags are properly closed.
 */
function _html5_tools_filter_htmlcorrector($text) {
  return html5_tools_filter_dom_serialize(html5_tools_filter_dom_load($text));
}
```

**Comment by sylus** [comment]
I believe I have reduced it down to this:

```
  $html5 = html5_tools_get_html5_instance();
  $text = <<<EOL
<!DOCTYPE html>
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head>
<body>
<address>Example</address>
<video src="http://www.google.com">&nbsp;</video>
</body>
</html>
EOL;

  $dom_document = $html5->loadHTML($text);
  $body_node = $dom_document->getElementsByTagName('body')->item(0);
  $html5 = html5_tools_get_html5_instance();
  foreach ($body_node->childNodes as $child_node) {
    $body_content .= $html5->saveHTML($child_node);
  }
```

Where $body_content is returned as:

```sh
<address>DDDD
<video src="http://www.google.com">&nbsp;</video>
```

**Comment by sylus** [comment]
When I changed the following:

```sh
        "address" => 89, // NORMAL | VOID_TAG | AUTOCLOSE_P | BLOCK_TAG
```

to

```sh
        "address" => 65,
```

I then got correct output.

**Comment by mattfarina** [comment]
Looking at the [spec for address](https://www.w3.org/TR/html5/sections.html#the-address-element) I see that neither the start or end tag can be omitted. I'm not sure why `AUTOCLOSE_P` is on this. I think that's what's causing this issue.

@sylus Do you want to update this on master and the 2.x branch or shall I? I'm always open to PRs.

```php
    "address" => 65, // NORMAL | BLOCK_TAG
```

**Comment by sylus** [comment]
Thanks a bunch submitted a P.R. ^_^

**Comment by mattfarina** [comment]
Version 2.2.1 has been released with this fix included. Thanks for the contribution.

**Comment by sylus** [comment]
Thank you for the awesomeness that is html5-php ^_^!
