### ISSUE TITLE
Line numbers are always zero

### ISSUE THREAD

**Issue by sidkshatriya** [Masterminds/html5-php#113]
We're using this library in the https://github.com/Lullabot/amp-library project. 

The approach in a super simplified fashion is:

```php
$document = '<!doctype html><html>...etc. etc...</html>';
// Notice, not using QueryPath::withHTML5
$qp = QueryPath::withHTML($document, NULL, ['convert_to_encoding' => 'UTF-8']);
...
// validate this code for AMP HTML standards issues
// Output problems with **line numbers** and try to fix them if at all possible
// see https://github.com/Lullabot/amp-library#using-the-command-line-amp-console for example
...
$qp->top()->html5(); // Uses mastermind HTML 5
```

Notice we only use the mastermind library for html5 output. We're using the normal PHP dom html parser for input.

It might be a good idea to use `mastermind/html5-php` for parsing the HTML as well. This seems to deal with cases like the `<source src="foo.wav" type="audio/wav">` tag for instance which the default PHP dom parser seems to have problems with. (PHP DOM wants something like  `<source src="foo.wav" type="audio/wav"></source` ).

There is one major problem though: We use [`DOMNode::getLineNo()`](http://php.net/manual/en/domnode.getlineno.php) extensively to point out where problems are occurring during the validation phase.

Now if we were to replace `QueryPath::withHTML` with `QueryPath::withHTML5` suddenly all the line numbers become 0 (i.e. `DOMNode::getLineNo()` always returns 0). I'm guessing this is happening because the HTML5 parser is parsing the html5 document and destroying original information on line numbers by making this a 1 line string. Or is this a bug?

There are some ways to get around this problem but they require additional programming e.g. 

Possible approach:
```
foreach tag in the PHP DOM of the HTML5 parsed document: 
 - Every time we see the next tag, we search forward for the same tag name in the original document string 
   - If while searching forward you see a new line(s), increase the current line count by that many lines
   - When you find the tag name you were looking for, save the character position. (Next time resume search from the same position)
   - Associate the current line count with the current tag you see
```

As you can imagine this could get tricky in some cases e.g. the parser decides to reject some HTML in case the document was slightly malformed. Then the association between original line numbers and DOMNode tags can get a bit off.

Is there a simpler way to do this? How can I have line numbers (the original document line numbers) in the least painful way? 

(Thanks for your help on #98 earlier BTW)

**Comment by sidkshatriya** [comment]
The other approach would be to simply close tags like `<track>` , `<source>` etc. by some code (any libraries you think might be useful?) and use the PHP DOM HTML parser as before, I guess...

**Comment by sidkshatriya** [comment]
@mattfarina Any hints on `DOMNode::getLineNo()` always being 0 and a way to get line numbers from original document?

**Comment by sidkshatriya** [comment]
I have been able to find a workaround for line numbers being always zero.

Lets say my original html is 
```html
<html>
<body>
<p>hello</p>
</body>
</html>
```

Before sending it to QueryPath::withHTML5() I change it to:

```html
<html data-amp-lineno="1">
<body data-amp-lineno="2">
<p data-amp-lineno="2">hello</p>
</body>
</html>
```

In other words I simply add an attribute to each tag corresponding to the original document line number. Even if `mastermind/html5-php` internally squishes everything to a single line, I always have a line number corresponding to original document available by looking at the attribute.

This seems to be working properly. I'm closing this ticket. Do reopen if another (better) workaround is available.

**Comment by mattfarina** [comment]
@sidkshatriya Sorry for the slow response. I've was traveling and then the holiday weekend put me behind on these issues.

I don't believe there is a way to set the line number returned by `DOMNode::getLineNo()`. If there is one I have a couple ideas how to figure it out. But, as far as I can tell (and someone please correct me if I'm wrong) there isn't a way to set that from PHP. It's part of libxml that's not exposed.

I'm happy to try and fix this if it's possible.

**Comment by sidkshatriya** [comment]
@mattfarina I have implemented a workaround (whose broad sketches were described in https://github.com/Masterminds/html5-php/issues/113#issuecomment-221214077 . 

The final solution involves subclassing some classes from your `Masterminds/html5-php`

FWIW here are some relevant links that will show you how I did it.
(Main logic here)
https://github.com/Lullabot/amp-library/blob/master/src/Utility/AMPDOMTreeBuilder.php#L68

Related subclasses:
https://github.com/Lullabot/amp-library/blob/master/src/Utility/AMPHTML5.php
https://github.com/Lullabot/amp-library/blob/master/src/Utility/AMPTokenizer.php

Once I add the line number attribute, its available for me to extract in the future.

**Comment by aleksblendwerk** [comment]
Sorry for resurrecting this ancient issue but I would also love to see some 'native' way to get ahold of the line number in this project.

For now I guess I will get to work on a similar workaround as described by @sidkshatriya (thanks for that).
