### ISSUE TITLE
Preserve case sensitive tag names

### ISSUE THREAD

**Issue by hason** [Masterminds/html5-php#114]
Current behaviour: ``<Button color="red">Error</Button>`` -> ``<button color="red">Error</button>`` .
Expected behaviour: ``<Button color="red">Error</Button>`` -> ``<Button color="red">Error</Button>` .

**Comment by goetas** [comment]
:+1:  will check as soon as possible

**Comment by goetas** [comment]
Case sensitive tags are only in XML mode https://www.w3.org/TR/html-markup/documents.html#conformant-xml

Currently not yet implemented, but most likely will reuse `xmlNamespaces` option

**Comment by goetas** [comment]
Fix https://github.com/Masterminds/html5-php/pull/116
