### ISSUE TITLE
sadly I don't get it working on a fragment :/

### ISSUE THREAD

**Issue by CanRau** [Masterminds/html5-php#125]
hey guys, just installed composer and html5-php and switched my code, which formerly used simple_html_dom, to work with your library

my html is a string of paragraphs `<p>` like `<p>paragraph</p><p>paragraph2</p>` and so on
I tried the following

    $html5 = new HTML5();
    $dom = $html5->loadHTMLFragment($content);
    $paragraphs = $dom->getElementsByTagName('p');
    var_dump($paragraphs);

as this would be more or less DOMDocument syntax, but it throws the following error

> Fatal error: Uncaught Error: Call to undefined method DOMDocumentFragment::getElementsByTagName
then I stumbled upon ownerDocument somewhere so tried this

    $html5 = new HTML5(['disable_html_ns' => true]);
    $dom = $html5->loadHTMLFragment($content);
    $paragraphs = $dom->ownerDocument->getElementsByTagName('p');
    var_dump($paragraphs);

not throwing any errors but `$paragraphs` remains empty
next step would be to iterate paragraphs and get all `<img` nodes

what am I doing wrong?

**Comment by goetas** [comment]
The returned element by `loadHTMLFragment` is not a DOM. It's is a `DOMDocumentFragment`.
This has many implications.

```php
$html5 = new HTML5(['disable_html_ns' => true]);
$fragment = $html5->loadHTMLFragment($content); // $fragment is not a DOM

$dom = new DOMDocument(); // create a DOM
$dom->appendChild($dom->importNode($fragment, true)); // and add to it the fragment

$paragraphs = $dom->getElementsByTagName('p'); // query
var_dump($paragraphs); // now you should have what you expect 
```


a bit different approach (but depends on your usecase) can be (might not work if you have to merge multiple fragments):

```php
$html5 = new HTML5(['disable_html_ns' => true]);
$fragment = $html5->loadHTMLFragment($content); // $fragment is not a DOM

$dom = $fragment->ownerDocument; // take a reference to the inner anonymous DOM
$dom->appendChild($fragment); // add it to the inner DOM

$paragraphs = $dom->getElementsByTagName('p'); // query
var_dump($paragraphs); // now you should have what you expect 
```
