### ISSUE TITLE
How to use it without composer?

### ISSUE THREAD

**Issue by peixotorms** [Masterminds/html5-php#126]
Hi, can you provide instructions on how to use this without composer please?

**Comment by goetas** [comment]
Using this project without composer is not officially supported.

Nowadays composer is the standard to manage dependencies for php. 

Any specific reason to not use composer? The integration of composer is generally pretty easy

**Comment by peixotorms** [comment]
I want to include this on a wordpress plugin and for compatibility, I would rather simply include the needed files... I understand if it's not supported, but in that case I'll have to go through the code and find a way. Thanks anyway for the prompt reply.

**Comment by mundschenk-at** [comment]
@peixotorms Have a look at how I do it in [wp-Typography](https://github.com/mundschenk-at/wp-typography). (Although if you include html5-php in the same manner, our plugins will probably not be compatible with each other.)

**Comment by Joshdw** [comment]
For anyone stumbling upon this years later, here's how to use require version of this without composer.

`
    require_once("./HTML5.php");
    require_once("./HTML5/Elements.php");
    require_once("./HTML5/Entities.php");
    require_once("./HTML5/Exception.php");
    require_once("./HTML5/InstructionProcessor.php");
    require_once("./HTML5/Parser/EventHandler.php");
    require_once("./HTML5/Serializer/RulesInterface.php");
    require_once("./HTML5/Parser/InputStream.php");
    require_once("./HTML5/Parser/StringInputStream.php");
    require_once("./HTML5/Parser/Scanner.php");
    require_once("./HTML5/Parser/Tokenizer.php");
    require_once("./HTML5/Parser/TreeBuildingRules.php");
    require_once("./HTML5/Parser/UTF8Utils.php");
    require_once("./HTML5/Serializer/HTML5Entities.php");
    require_once("./HTML5/Serializer/OutputRules.php");
    require_once("./HTML5/Serializer/Traverser.php");
    require_once("./HTML5/Parser/DOMTreeBuilder.php");
    require_once("./HTML5/Parser/FileInputStream.php");
    require_once("./HTML5/Parser/ParseError.php");
    require_once("./HTML5/Parser/CharacterReference.php");
	
    $html5 = new Masterminds\HTML5();
    $dom = $html5->loadHTMLFragment('<p>test</p>');
	
    $result = $html5->saveHTML($dom);
`
