### ISSUE TITLE
any loadHTML options for not adding a default doctype

### ISSUE THREAD

**Issue by shtse8** [Masterminds/html5-php#128]
as DOMDocument provide this options as follows:
```php
$document = new DOMDocument();
$doc->loadHTML($html, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD | LIBXML_COMPACT | LIBXML_NOENT );
```

I want to do the same thing, when there is missing DOCTYPE, don't add it, any advise?

**Comment by shtse8** [comment]
This project is the best I have ever used. But I don't want it to repair my source html and just doing some manipulations.

**Comment by goetas** [comment]
Can't understand. You want the doctype in output or not?

**Comment by shtse8** [comment]
I want html5-php can provide the following two libxml options so we can choose to add or not when there are missing html/body/doctype. 

I am doing a project to minify the html code using this project, because the DOMDocument is failed to handle utf-8 correctly, but this project is adding the doctype automatically when it is missing. Actually I don't know the input in my project, so I don't know if it is a fragment or a document.

Reference from PHP Doc:
http://php.net/manual/en/libxml.constants.php

```
LIBXML_HTML_NOIMPLIED (integer)
Sets HTML_PARSE_NOIMPLIED flag, which turns off the automatic adding of implied html/body... elements.
```

```
LIBXML_HTML_NODEFDTD (integer)
Sets HTML_PARSE_NODEFDTD flag, which prevents a default doctype being added when one is not found.
```


Expected Code:
```
$html5 = new HTML5([ 'noimplied' => true, 'nodefdtd' => true ]);
$document = $html->loadHTML("<body>Body</body>");
$html5->saveHTML($document);
``

Expected Output:
```
<body>Body</body>
```

**Comment by goetas** [comment]
Actually the exact feature that you are looking for is not really available.

But some of them are:

To load only a portion of a document (witout having the html/head tags injected) you can use `HTML5::loadHTMLFragment()` method. This should be enough for your case

**Comment by mundschenk-at** [comment]
@shtse8 You could also do what I do in wp-Typography: [Add the `<!DOCTYPE>` and `<html><body>` tags to the fragment](https://github.com/mundschenk-at/wp-typography/blob/master/php-typography/class-php-typography.php#L936), but [save only the children of the the body tag](https://github.com/mundschenk-at/wp-typography/blob/master/php-typography/class-php-typography.php#L808) on retrieval.

You could do a pattern match on the string beforehand to check if it's a document or a fragment.

**Comment by shtse8** [comment]
Thanks for your advise.

@mundschenk-at @goetas 
I can't use this method because there is a case the input has the doctype or html/body. I have to read the doctype or html/body if they exists.

Expected Code:
```php
$html5 = new HTML5([ 'noImplied' => true, 'noDefDTD' => true ]);
$document = $html->loadHTML("<!DOCTYPE html><body>Body</body>");
echo $html5->saveHTML($document);
```

Expected Output:
```html
<!DOCTYPE html><body>Body</body>
```

**Comment by goetas** [comment]
```html
<!DOCTYPE html><body>Body</body>
```

Is not a valid HTML5 document...

**Comment by shtse8** [comment]
I understand, but as I'm making a minifier ( the aim is to minify code ), users don't expect it will repair the code or add the html/head by default. I can do it with `DOMDocument` because they have the options to not adding it if they doesn't exist, but it fails to handle UTF-8 and some HTML5tags correctly. I found this project can handle well but missing these two options.

**Comment by mundschenk-at** [comment]
@shtse8 That will not work. Code that is not well-formed will always be "repaired" by the parser.

**Comment by goetas** [comment]
@mundschenk-at 
> That will not work. Code that is not well-formed will always be "repaired" by the parser.

true true

**Comment by shtse8** [comment]
Thanks again.
So how to write a function to check if the input is fragment or not before parsing the html?
I don't really understand, is it checking the existence of doctype and only one `html` root? how about body and head? Do I need to check? If I have to check I would like to use `preg_match`, but how to confirm it is in a good order without parsing it?
Before, I want to parse it first and see if there is a fragment or not and try to repair the code. But at the moment, it is repaired by default, I cannot do the checking so I have to check before `loadHTML` or `loadHTMLFragment`. Any advise?

**Comment by mundschenk-at** [comment]
The problem is not the check for `DOCTYPE` and/or `body` resp. `html`, that should be easy (if not efficient) with `preg_match`. The problem is that what you intend to do, make a minimizer that does not "fix" HTML code, will not work because saving a DOM parsed from invalid HTML code will not result in the same code.

**Comment by shtse8** [comment]
As `loadHTMLFragment` will remove the `doctype` and `loadHTML` will add the `doctype`, I am going to crate a method to check the input if it is a fragment or not. But the problem is how can I do this before parsing it? I think `preg_match` cannot do it well because it is just only to match the string but don't know if it is in a good structure. For my suggestion, `html5-php` is better to give an option to repair or not. Therefore, we can do know if the input is a valid html5 and choose to output it as a fragment or a document.
