### ISSUE TITLE
Handle illegal self-closing according to spec

### ISSUE THREAD

**Issue by apeschar** [Masterminds/html5-php#136]
Browsers will parse

~~~html
<div />
<span>Hello, World!</span>
</div>
~~~

like this ([proof](https://jsfiddle.net/3h0owjw8/))

~~~html
<div>
<span>Hello, World!</span>
</div>
~~~

Whereas this parser will parse it like this

~~~
<div></div>
<span>Hello, World!</span>
~~~

This is because the `Tokenizer` emits `endTag` after all self-closing tags. It should really only do this for tags that may be self-closed (ie, [void elements and foreign elements](https://www.w3.org/TR/html5/syntax.html#start-tags)).

**Comment by goetas** [comment]
This makes sense but most probably is a BC break :crying_cat_face:

**Comment by mundschenk-at** [comment]
Is it rally a BC break if the parser gets closer to spec (or browser behavior, as an extension of the spec)?

**Comment by apeschar** [comment]
Right. The README starts with "HTML5 is a standards-compliant HTML5 parser". It isn't quite, but fixing this bug would get it a little closer.

**Comment by apeschar** [comment]
See the URL I linked in my PR. Self-closing tags _do not exist_ in HTML, are an error, and therefore ignored by browsers, except for foreign elements.

See also: https://www.w3.org/TR/html5/syntax.html#start-tags
