### ISSUE TITLE
Undefined index: in vendor/masterminds/html5/src/HTML5/Parser/DOMTreeBuilder.php:322

### ISSUE THREAD

**Issue by asokol1981** [Masterminds/html5-php#140]
Hello.
The error is caused by `$this->nsStack[0]['']`. But it's impossible that the element of this array is not defined.
Unfortunately I can't reproduce it permanently. The first time script throws an error, the second - not. Where to dig? Could this be caused by opcache or some kind of php bug? What you think?

**Comment by goetas** [comment]
Pobably  `$this->nsStack[0]['']` is not defined (in https://github.com/Masterminds/html5-php/blob/441fb2bc82599e4e3e90ee94d0f084649f4952f2/src/HTML5/Parser/DOMTreeBuilder.php#L322)

**Comment by goetas** [comment]
Can you verify?

**Comment by asokol1981** [comment]
Yes, it is. But I can't find a way how it can to happen.

**Comment by asokol1981** [comment]
Any suggestions?

**Comment by tgalopin** [comment]
Would you have the HTML to reproduce? This could be a useful first step :) .

**Comment by asokol1981** [comment]
Thank you for response.
Unfortunately this behavior doesn't depend on HTML. I saw these errors on different markup. It is strange, that the second processing works without errors.
So I did a workaround:
```php
$html5 = new HTML5([
    'encode_entities' => false,
    'disable_html_ns' => true,
]);

try {
    // First run.
    return $html5->loadHTML($string);
} catch(Exception $e) {
    // Without reset it may throw error again.
    opcache_reset();

    // Start parse again.
    return $html5->loadHTML($string);
}
```

**Comment by asokol1981** [comment]
Thank you for response.
Unfortunately this behavior doesn't depend on HTML. I saw these errors on different markup. It is strange, that the second processing works without errors.
So I did a workaround:
```php
$html5 = new HTML5([
    'encode_entities' => false,
    'disable_html_ns' => true,
]);

try {
    // First run.
    return $html5->loadHTML($string);
} catch(Exception $e) {
    // Without reset it may throw error again.
    opcache_reset();

    // Start parse again.
    return $html5->loadHTML($string);
}
```

**Comment by tgalopin** [comment]
Any idea for the reason?

**Comment by asokol1981** [comment]
I think the reason is opcache.
