### ISSUE TITLE
Get rid of libxml dependency

### ISSUE THREAD

**Issue by alecpl** [Masterminds/html5-php#174]
I don't see anything in the code that would require libxml extension. We only need DOM. Do I miss something?

**Comment by alecpl** [comment]
I see utf8_decode(), but preceded with function_exists() check, so composer.json should not require libxml.

**Comment by goetas** [comment]
I think that here the intention was to require `ext-dom`. Probably is a bug. 
(even if having ext-dom implies installing `libxml`... 

I will be happy to change it. Can you reproduce it somehow on travis ci? removing libxml, but keeping extdom?

**Comment by alecpl** [comment]
No, I didn't try with Travis, that came from one of Roundcube users.

**Comment by alecpl** [comment]
Actually, the ctype ticket came from the user. This one is from me just reviewing dependencies.
