### ISSUE TITLE
DOMCdataSection vs DOMText

### ISSUE THREAD

**Issue by bytestream** [Masterminds/html5-php#175]
I've come across a discrepancy between DOMDocument and this lib:

DOMDocument returns `DOMCdataSection` for the `<style>` content

```php
$dom = new \DOMDocument;
$dom->loadHTML('<!doctype html>
    <html lang="en">
      <head>
        <style type="text/css"><!--
div {}
--></style>
      </head>
      <body>
        <div id="foo" class="bar baz">foo bar baz</div>
      </body>
    </html>');

var_dump( $dom->getElementsByTagName('style')->item(0)->childNodes->item(0) ); die;
```

masterminds/html5 return `DOMText` for the `<style>` content

```php
$dom = $this->html5->loadHTML(
            '<!doctype html>
    <html lang="en">
      <head>
        <style type="text/css"><!--
div {}
--></style>
      </head>
      <body>
        <div id="foo" class="bar baz">foo bar baz</div>
      </body>
    </html>');

var_dump( $dom->getElementsByTagName('style')->item(0)->childNodes->item(0) ); die;
```

DOMDocument treats this has `DOMCdataSection`

> In HTML, the content of the script and style elements is treated as if it were CDATA, so that & and < are not special except when they occur as the end tag to close the element.

I think `DOMText` and probably `DOMCdataSection` are incorrect. Although, mimicking `DOMDocument` is probably what's intended?

At the very least it should be tokenized as `DOMComment`. 

> However, when using the <style> element, you may use  to hide CSS from older browsers, although this is not recommended.

This is indeed valid HTML5 when validated at https://validator.w3.org/

**Comment by goetas** [comment]
`Masterminds/html5-php` returns a `DOMDocument` object, but this does not mean that the object structure has to be the same as what `DOMDocument::loadHTML` will do. 

`style` ans `script` are special type of nodes and they do not follow the traditional XML-ish parsing rules. Consider also that [HTML5 does not have at all concept of CDATA](https://stackoverflow.com/questions/3302648/should-i-use-cdata-in-html5/11462560).

What is inside the `style` node is CSS, and HTML comments are not allowed,  same goes for `script`. 
HTML5 is not XHTML.
