### ISSUE TITLE
Disable line ending normalisation

### ISSUE THREAD

**Issue by bytestream** [Masterminds/html5-php#176]
https://github.com/Masterminds/html5-php/pull/146 added [replaceLineFeeds](https://github.com/Masterminds/html5-php/pull/146/files#diff-81f4b1589fd833d87d4fe5dea481eb82R310)

Feature request, to turn this off? not sure if it's affects the performance improvement?

**Comment by goetas** [comment]
This could be implemented as some sort of feature flag. 
Performance will probably get worse since now there are two different chars to search for.

Feel free to send an implementation for this.

**Comment by bytestream** [comment]
Looks like the spec disallows CR characters https://html.spec.whatwg.org/multipage/parsing.html#preprocessing-the-input-stream
