### ISSUE TITLE
Add option to parse html without adding doctype + html + body

### ISSUE THREAD

**Issue by ERROPiX** [Masterminds/html5-php#180]
`loadHTML()` force adding of doctype, HTML tag, and body tag when loading partial HTML string

Is there any way to do the same as 
```php
$dom->loadHTML($output, LIBXML_HTML_NODEFDTD | LIBXML_HTML_NOIMPLIED);
```

**Comment by goetas** [comment]
have you tried `loadHTMLFragment()`?

**Comment by ERROPiX** [comment]
@goetas yes, 
The issue is that it create a `DOMDocumentFragment` instead of `DOMDocument`, and I can't use DOMXpath query on it

is there a way to apply `XPath::query`?

**Comment by goetas** [comment]
You can do this: 

```php
$doc = new DOMDocument();

$htm5 = new Html5([
  'target_document' => $doc
]);

$frag = $htm5->loadHTMLFragment('html here...');

$doc->appendChild($frag);

$xpath = new DOMXpath($doc);

$el = $xpath->query('/div');
```

**Comment by mundschenk-at** [comment]
@ERROPiX See https://github.com/mundschenk-at/php-typography/blob/master/src/class-php-typography.php#L251 for another workaround.
