### ISSUE TITLE
Increase minimum PHP requirement to allow more modern code

### ISSUE THREAD

**Issue by mundschenk-at** [Masterminds/html5-php#189]
Currently, library requires PHP 5.3. This should be changed to at least PHP 5.6 to [allow the use of more modern language features](https://github.com/Masterminds/html5-php/pull/187#discussion_r448371192). Since even PHP 5.6 has [not received security updates for more than 18 months](https://www.php.net/supported-versions.php), this would not be a radical change.

**Comment by goetas** [comment]
I thought in the past about it, but so far  there has been not a single feature that required more advances PHP syntax that wasn't available with php 5.3.

I'm willing to increase the version requirements if there will be some feature proposal that will need some of the more recent php features, but I'm not willing to increase the minimum version just for the sake of it.

(as example one large project that uses this library is Roundcube mail, and it requires php 5.4, so increasing too the php requirements will put such project is a difficult situation, and many other project that use this library work in contexes where increasing php version is not an easy thing)

**Comment by mundschenk-at** [comment]
> I'm willing to increase the version requirements if there will be some feature proposal that will need some of the more recent php features, but I'm not willing to increase the minimum version just for the sake of it.

5.5 is needed to properly use exceptions (try ... finally). I've linked to the code proposal in question.

> (as example one large project that uses this library is Roundcube mail, and it requires php 5.4, so increasing too the php requirements will put such project is a difficult situation, and many other project that use this library work in contexes where increasing php version is not an easy thing)

Well, it's not that previous versions suddenly vanish. Nudging the community to reduce technical debt (by, from time to time, increasing version requirements), is something that I feel large projects have duty to do, to lead by example. Running PHP versions below even 5.6 is irresponsible from a security perspective.

**Comment by goetas** [comment]
> 5.5 is needed to properly use exceptions (try ... finally). I've linked to the code proposal in question.

The code suggested in https://github.com/Masterminds/html5-php/pull/187#discussion_r448496044 does exactly the same without using the `finally` keyword.

>Well, it's not that previous versions suddenly vanish.

They do not vanish, but siad projects will see suddenly disappear the "support" given by this project in providing bugfixes on this library.

I know that the minimumu supported version is a hot topic, In which I believe too. You can see that most of the projects I maintain require at least php 7.2, but this project is particular and used often in contexts where php versions are not that recent.
