### ISSUE TITLE
How to disable DOCType, HTML, HEAD & BODY tag

### ISSUE THREAD

**Issue by th3-sh0w3r** [Masterminds/html5-php#196]
Hey,

how do I disable the (DOCType, HTML, HEAD & BODY tags)?
I just want that my Input is the same as my output.

Now:
  ```
Input: <div><p>Test</p></div>
  Output: <DOCTYPE><html><head></head><body><div><p>Test</p></div></body></html>
```

What I want:
  ```
Input: <div><p>Test</p></div>
  Output: <div><p>Test</p></div>
```

**Comment by drtheuns** [comment]
Seems to work fine for me:

```php
$html5 = new HTML5();
$dom = $html5->loadHTMLFragment('');
$html5->saveHTML($dom); // renders: <div><p>Test</p>p&gt;</div>div&gt;
```

No idea about those tags being escaped tho, first time looking at this libary.

**Comment by stof** [comment]
@goetas this issue should be closed as the answer has been provided.
