### ISSUE TITLE
Please update or delete the `2.x` branch

### ISSUE THREAD

**Issue by derrabus** [Masterminds/html5-php#209]
Hello 👋🏻 

This repository has a `master` branch that is aliased for composer as `2.7-dev` and a `2.x` branch. This leads Composer (and thus Packagist as well) to believe, the 2.x branch is ahead of the master branch. You can see this on the packagist page of this package.

<img width="162" alt="Bildschirmfoto 2021-06-22 um 17 24 25" src="https://user-images.githubusercontent.com/1506493/122953297-e407f980-d37e-11eb-83a7-b0282829f337.png">

The consequence is that if another project tries to install this package with `"masterminds/html5": "^2.7@dev"` or a similar constraint, Composer will pick the HEAD of the heavily outdated `2.x` branch because `2.x-dev` will always be considered to be ahead of `2.7-dev`. This is what happens in Symfony's CI for instance.

I don't know the reason for the current branching model, but my personal observation is that the `2.x` branch is obsolete and `master` is where the magic happens at the moment. This does not match Composer's expectation of the branches.

Because of that I'd like to suggest to…

* either merge `master` into `2.x` regularly
* or merge `master` into `2.x` once and switch development to the `2.x` branch
* or delete the `2.x` branch

**Comment by goetas** [comment]
@derrabus  I have deleted the outdated branch, can you let me know if the issue is fixed for you?

**Comment by goetas** [comment]
BTW i have released https://github.com/Masterminds/html5-php/releases/tag/2.7.5

**Comment by derrabus** [comment]
> I have deleted the outdated branch, can you let me know if the issue is fixed for you?

It is, thank you very much!
