### ISSUE TITLE
is adding html tags and converting > with &gt

### ISSUE THREAD

**Issue by mbarreiro85** [Masterminds/html5-php#210]
Hi there, thanks for your work with this package, im having some problems with it, but im parsing php files worse than that blade files and i need help starting with 2 situations

1 - Is any way to stop adding html tags to php files
2 - It is enconding > with &gt with encode option disable

regards

**Comment by stof** [comment]
Please provide an actual reproducer. There is not enough info to help here.

**Comment by goetas** [comment]
this looks a generic support request rather than an issue in this project. if you have an reproducible issue, please create a more specific ticket on github
