### ISSUE TITLE
PHP 8.1 deprecated notice

### ISSUE THREAD

**Issue by igumnovaleksey** [Masterminds/html5-php#230]
The following deprecated notices were found while using the phpstan tool:

all/libraries/composer/vendor/masterminds/html5/src/HTML5/Parser/StringInputStream.php
180 line Return type mixed of method Masterminds\HTML5\Parser\StringInputStream::current() is not covariant with tentative return type mixed of method Iterator::current().
189 line Return type mixed of method Masterminds\HTML5\Parser\StringInputStream::next() is not covariant with tentative return type void of method Iterator::next()
197 line Return type mixed of method Masterminds\HTML5\Parser\StringInputStream::rewind() is not covariant with tentative return type void of method Iterator::rewind()
207 line Return type mixed of method Masterminds\HTML5\Parser\StringInputStream::valid() is not covariant with tentative return type bool of method Iterator::valid()
327 line Return type mixed of method Masterminds\HTML5\Parser\StringInputStream::key() is not covariant with tentative return type mixed of method Iterator::key()

**Comment by PavelSPN** [comment]
Hi [igumnovaleksey](https://github.com/igumnovaleksey)!

To be more compatible with previous versions of PHP (for example the type "mixed" available as of PHP 8.0.0) it would be better to use

#[\ReturnTypeWillChange]
