### ISSUE TITLE
Whitespace in the end tag of RCDATA tags

### ISSUE THREAD

**Issue by zhaofengli** [Masterminds/html5-php#75]
The parser is confused if you add whitespaces into `</title>`, like:
```html
<title>Note the space after "title"</title >
<title>Another example<title
>
```
Both examples above are valid according to the W3 Validator.

This behaviour is caused by [Tokenizer.php](https://github.com/Masterminds/html5-php/blob/master/src/HTML5/Parser/Tokenizer.php#L203) which assumes the end tag is always exactly `</title>`.

## Test script
```php
<?php
require_once __DIR__ . "/vendor/autoload.php";
$html = <<<EOF
<!doctype html>
<html>
<head>
	<title>This is valid, really.</title >
</head>
<body></body>
</html>
EOF;
$parser = new Masterminds\HTML5;
$dom = $parser->loadHTML( $html );
echo $parser->saveHTML( $dom );
```
### Output
```
<!DOCTYPE html>
<html><head>
	<title>This is valid, really.&lt;/title &gt;
&lt;/head&gt;
&lt;body&gt;&lt;/body&gt;
&lt;/html&gt;</title></head></html>
```
## Real-world examples
- http://www.infoplease.com/ipa/A0855613.html

**Comment by technosophos** [comment]
This looks good to me. Good catch. And thanks for including the tests.
