### ISSUE TITLE
characters following an ampersand are removed if it is not encoded prior to parsing

### ISSUE THREAD

**Issue by mattbucci** [Masterminds/html5-php#78]
noticed an issue on our site today.

we had the characters R&D in our html. Obviously this should be R &a mp; D to be accurate, however when html5-php parses this, it parses it to R&amp;

I'm assuming this is because &D isn't an html entity so it defaults to the &amp; I would have expected the output to be R &a mp; D though.

**Comment by mattfarina** [comment]
I can reproduce this. It appears to be a problem in the entity parsing code.

**Comment by mattfarina** [comment]
@mattbucci There is a fix on master. Please give this a try and let me know if there are any problems.
