### ISSUE TITLE
Very long-running

### ISSUE THREAD

**Issue by itmen669** [Masterminds/html5-php#80]
Source:
![image](https://cloud.githubusercontent.com/assets/10218654/6692562/650282ca-ccde-11e4-9e09-defe790d79f0.png)
Output:
![image](https://cloud.githubusercontent.com/assets/10218654/6692584/861ce52c-ccde-11e4-8011-792b637821e3.png)

$html contains doctype HTML 4.01, total size 37 KB

**Comment by goetas** [comment]
Can you test separately the load and save methods?
Il 17/mar/2015 17:52 "Michael" <notifications@github.com> ha scritto:

**Comment by mattfarina** [comment]
@Itmen669 could you share your example HTML? I would be curious to run some of my own numbers on it to trace what's going on.

**Comment by Itmen669** [comment]
@mattfarina aww, I was getting html from a third-party site. http://yaplakal.com
HTML can be changed over time, sorry.

**Comment by goetas** [comment]
I've tested this issue. Downloading some fresh HTML from http://yaplakal.com.

The size of the document was 243k.

The time to parse the document on my laptop (Intel I3) was: 

~50s with XDebug **enabled*
~4s with XDebug **disabled**

Conclusion: do not use XDebug on production servers.

**Comment by mattfarina** [comment]
~4s seems like a long time.

@goetas with xdebug did you map out where the time is being spent? I wonder if there are ways to make it faster.

**Comment by goetas** [comment]
Running the same test on travis, https://travis-ci.org/Masterminds/html5-php/builds/58058822 we have different timings.

Version | Time
------------ | -------------
5.3| ~7s
5.4| ~7s
5.5| ~4s
5.6| ~4s
hhvm| ~0.8s
7| ~0.5s

Looking at the xdebug profiller:
- 48% of running time is consumed by `Tokenizer.php`  (here we have a lot string concatenation, known to be slow, but i tried to change it to arrays, but no big wins)
- 44% of running time is consumed by `Scanner.php` (most consumked by `Scanner::current()` method, rhere is a lot of indexed string access... do not know if it can be optimized easily)

**Comment by mattfarina** [comment]
I just pulled the html from http://yaplakal.com and ran some tests locally against master. I was consistently getting around ~0.6s (without xdebug). The file is about 224kb. This was with php 5.5.

I'm not sure what to do with this issue at this point? The scanner uses the input streams and there is an issue to re-write the file one which may be an improvement.

Any suggestions on actions or is this in a state where we should close it?

**Comment by scratcher28** [comment]
I am having a lot of issues with out-of-memory, even when parsing relatively small piece of html code (less than 200kb).

**Comment by goetas** [comment]
Can you share the code?

**Comment by goetas** [comment]
no feedabck
