### ISSUE TITLE
UTF8Utils::countChars() - extra bad perfomance with iconv_strlen()

### ISSUE THREAD

**Issue by layershifter** [Masterminds/html5-php#94]
Hi :)

When I try load page with library, I receive:
Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/storage/vendor/masterminds/html5/src/HTML5/Parser/UTF8Utils.php on line 52

It's very strange to receive this on i7-6700.

On line 52 we have iconv_strlen($string, 'utf-8'), it is a source of problems. Source page in UTF-8, if this is important.

When I replace it with mb_strlen, everything is fine - page loads for milliseconds. It seems that problem in iconv_strlen().

----

Proposal: replace iconv_strlen() with mb_strlen(), it's supported in all modern PHP versions (PHP 4 >= 4.0.6, PHP 5, PHP 7).

**Comment by goetas** [comment]
solved in https://github.com/Masterminds/html5-php/issues/95
